#!/usr/bin/env bash

echo XXX sub_test
echo -n "XXX make: "
which make
echo -n "XXX pwd: "
pwd
echo -n "XXX chpl: "
which chpl

export CHPL_COMPILER=$1
make

# Runs all *.py files in the current directory.

dirs=$CHPL_HOME/util/chplenv:$CHPL_HOME/util/test
export PYTHONPATH=${PYTHONPATH:+${PYTHONPATH}:}$dirs

export PATH=${PATH:+${PATH}:}$CHPL_HOME/util/config

for file in *.py; do
    python3 $file $@ ${EXECOPTS} -v
done
